# This workflow will build all C/C++ project with make

name: Build C/C++ snippets

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        module: [ segment ]
    steps:
      - name: Checkout sources for ${{matrix.module}}
        uses: actions/checkout@v6
      - name: Make ${{matrix.module}}
        run: make
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.module }}
          path: ${{ matrix.module }}
